version: "3.9"
services:
  server-test-webapp:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: server-test-webapp
    container_name: server-test-webapp
    image: javawiki/server-test-webapp:1.2.0
    ports:
      - "40141:9800"
    restart: "always"
    healthcheck:
      test: "curl -f http://localhost:9800/actuator/health || exit 1"
      start_period: 60s
      interval: 30s
      timeout: 60s
      retries: 6
    environment:
      TZ: Asia/Shanghai
      SPRING_PROFILES_ACTIVE: dev
      JAVA_OPTS: -Dinfo.tags.environment=dev
