server:
  port: ${STW_SERVER_PORT:9800}

spring:
  application:
    name: server-test-webapp

logging:
  file:
    name: stw.log
  level:
    cn:
      netbuffer: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: @project.name@
    # read from environment
    version: ${APP_VERSION:v1.0.0}
  image:
    type: docker
    version: @project.version@