server:
  port: 9800

spring:
  application:
    name: server-test-webapp

logging:
  file:
    name: ${spring.application.name}.log
  level:
    cn:
      netbuffer: debug

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    env:
      enabled: true

info:
  app:
    name: @project.name@
  image:
    type: docker
    version: @project.version@